Allow repmgr node_id to take a starting seed value to ensure uniqueness in multi cluster environments
bitnami/bitnami-docker-postgresql-repmgr pull request #110
Opened 2022-02-02 03:22 UTC by ntejohn

The repmgr_get_node_id() function currently returns a node_id that starts from 1000 when the environment variable REPMGR_NODE_ID is not set. In this case, the REPMGR_NODE_NAME is used and the appended number is extracted, added to 1000 and returned. This is used when running the bitnami/postgresql-ha Helm chart for Kubernetes. The statefulset ordinal for each pod is used for the number added to 1000.
This change allows a number to be passed in through the new environment variable REPMGR_NODE_ID_START_SEED. This is the seed starting number for node_id. If nothing is passed in, the default number 1000 is used to start the count from. See the benefits section as it applies to multi cluster replicas.

This has been changed in all the postgresql versions 1011,12,13,14 and each tested with docker-compose and bitnami/postgresql-ha Helm chart. It has been tested with the new environment variable and without.

**Description of the change**

The change is to add an environment variable REPMGR_NODE_ID_START_SEED to the repmgr_get_node_id() function in the rootfs/opt/bitnami/scripts/librepmgr.sh script
The environment variable is also added to the rootfs/opt/bitnami/scripts/postgresql-env.sh script. 

**Benefits**

When using the bitnami Postgresql-ha Helm chart, multiple clusters can be deployed and connected as a single replicaset. In Kubernetes, the statefulset uses an ordinal in the name of each pod created, e.g pg-0, pg-1. This is the same in each cluster and with the repmgr_get_node_id() currently locked in to starting from 1000, this offers no uniqeness, so the cluster fails to form a replicaset successfully. In its current form for example, for 3 replicas in 2 clusters the the node_id's would be 1000,1001,1002 in one cluster and the same in the other cluster.

This change solves this problem by having the seed number passed in through the REPMGR_NODE_ID_START_SEED. As an example with 2 clusters consisting of ClusterA and ClusterB, each with 3 replicas, ClusterA could have as in the previous example, node_id's 1000,1001,1002 and given an example start id of 2000 for ClusterB, the node_id's would be 2000, 2001, 2002. Therefore all nodes have a unique repmgr node_id.

**Possible drawbacks**

As the default value is maintained if nothing is passed in, then this presents no drawbacks

**Applicable issues**

There is no current issue for this.

**Additional information**

Currently there doesn't appear to be a way to change the ordinal number in Kubernetes statefulset, or reliably read it, so that is what has prompted this change.
The bitnami/postgresql-ha helm chart be updated at a later stage but isn't essential immediately.

2022-02-02 11:31 UTC, alemorcuq requested changes
Thank you for the PR! Could you add the new variable to the README as well?

2022-02-02 11:31 UTC, alemorcuq commented on 11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh
> +            num=$((num+${REPMGR_NODE_ID_START_SEED:-1000}))
Since we are already setting the default value for the variable in the `postgresql-env.sh` file, I don't think we need to specify it here again.

2022-02-03 00:12 UTC, ntejohn commented on 11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh
> +            num=$((num+${REPMGR_NODE_ID_START_SEED:-1000}))
Ok, no problem, I'll add the variable to the readme and remove the default 1000 from the repmgr_get_node_id() function.

2022-02-03 06:36 UTC, ntejohn commented
I have made the changes as requested.

2022-02-03 11:16 UTC, alemorcuq approved these changes
Thanks!

2022-02-03 12:03 UTC, merged

2022-02-03 12:04 UTC, alemorcuq commented
A new version should be released in the following hours.