Added fencing mechanism for situation where failed primary occured.
bitnami/bitnami-docker-postgresql-repmgr pull request #112
Opened 2022-03-02 10:38 UTC by TK-Khaw

**Description of the change**
Repmgr provides ability to monitor for child nodes of a primary node and allows callback scripts to perform certain task since version 4.4. This PR uses the provided flexibility to fence the failed primary to avoid split-brain situation.  

 

**Benefits**
This PR will prevents possibility of split-brain situation by killing of primary node (aka STONITH) when the cluster clearly had moved on to a new primary. This issues had been raised several times in the Bitnami Helm charts postgresql-ha with example like issue created [here](https://github.com/bitnami/charts/issues/6555).

2022-03-04 16:06 UTC, rafariossaa commented
Hi,
  Thanks for providing this PR.
  Allow me to do some testing before merging.

2022-03-04 16:08 UTC, rafariossaa requested changes
You should add the new environment variables to the `postgresq-env.sh` file.

2022-03-05 02:16 UTC, TK-Khaw commented
hi @rafariossaa thanks for the reply. Allow me to look into it.

2022-03-08 07:18 UTC, TK-Khaw commented
Hi @rafariossaa sorry for the delay, I have updated `postgresql-env.sh` file with the new environment variables.

2022-03-08 14:31 UTC, rafariossaa commented
Hi,
  Thanks for adding it. 
  Would you mind to rebase  your changes ?  There is a conflict in the Dockerfiles.

2022-03-09 03:11 UTC, TK-Khaw commented
Hi I've merged the changes.

2022-03-09 14:51 UTC, rafariossaa requested changes
Sorry I did not mention these details before. Also take a look to the indentation, you should be using 4 spaces instead of tabs.

2022-03-09 14:51 UTC, rafariossaa commented on 10/debian-10/rootfs/opt/bitnami/scripts/postgresql-env.sh
> +export REPMGR_FENCE_OLD_PRIMARY="${REPMGR_FENCE_OLD_PRIMARY:-true}"
This should be a yes/no value, and I would suggest to set it by default to `false` to be consistent with the default value in the chart PR.

2022-03-09 14:51 UTC, rafariossaa commented on 10/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh
> +	if [[ "$REPMGR_FENCE_OLD_PRIMARY" == "true" ]]; then
This could be changed to:
```suggestion
        if is_boolean_yes "$REPMGR_FENCE_OLD_PRIMARY"; then
```
Take a look to my comment in `postgresql-env.sh`.

2022-03-10 02:04 UTC, TK-Khaw commented
oh thanks for noting the mistake, I have altered the code accordingly as well as for your suggestions.

2022-03-10 14:03 UTC, rafariossaa approved these changes
LGTM

2022-03-10 14:03 UTC, merged