Set wait counter for stopping service to 60s and fail if not terminated
bitnami/bitnami-docker-postgresql-repmgr pull request #41
Opened 2020-10-09 21:57 UTC by smueller18

A detailed explanation of the underlaying problem can be found at In https://github.com/bitnami/charts/issues/1880#issuecomment-698589171.

**Description of the change**
The wait counter for stopping services is set from 10s to 60s and an error is returned, if the process has not terminated.

**Benefits**
When using persistent storage in Kubernetes, access of files can be slowed down. The termination process of postgres during the initialization can take more than 10s. With this change, the container starts successfully even with a slower file system.

**Applicable issues**

Fixes https://github.com/bitnami/charts/issues/1880

2020-10-12 05:38 UTC, f0o commented
Increasing the sleep seems to work fine until that sleep isnt enough once again. Imagine a server getting an unusual load spike which slows down the container in that phase, 60s might not be enough all of a sudden.

It feels like an arms race to me, I wonder if there is any way that we could solve it by polling the DB or similar to ensure that we waited sufficient amount of time without fixating on a precise number

2020-10-12 05:39 UTC, f0o requested changes
Should be `#   Boolean`

2020-10-12 20:21 UTC, smueller18 commented
I think #42 is more elegant and should be preferred over this PR.

2020-10-13 10:20 UTC, FraPazGal commented
Hi @smueller18,

Thanks for the PR! If you want to leave this fix to the other PR, feel free to close this PR. Additionally, this is a known issue and we are also working on it internally as my colleague commented in the other PR, so it should be fixed fairly soon one way or another.

2021-04-21 01:25 UTC, closed without merging