Add variable to configure PostgreSQL server shutdown timeout
bitnami/bitnami-docker-postgresql-repmgr pull request #42
Opened 2020-10-12 15:42 UTC by enote-kane

**Description of the change**

Adds a new environment variable `` and modifies functions to allow specifying larger timeouts when stopping the PostgreSQL server.

**Benefits**

The PostgreSQL server shutdown timeout can now be increased to better handle environments with rather slow (or initially/temoprarily slow) storage infrastructure.

**Possible drawbacks**

Anything that uses the internal function `stop_service_using_pid` can now be sure that the process is stopped - either gracefully or forcefully (unless it is a zombie).

**Applicable issues**

* bitnami/charts#3986

2020-10-12 20:25 UTC, smueller18 commented
The default of `POSTGRESQL_SHUTDOWN_TIMEOUT` should be set at least to 60s. Otherwise many people have to customize the timeout from 10s to a larger number.

2020-10-12 21:36 UTC, enote-kane commented
I tend to personally agree, but then we also need to increase the `terminationGracePeriodSeconds` for the `StatefulSet` in the chart, since it defaults to 30 seconds which we certainly violate here at least for the primary.

So, let's keep it at 10 seconds here (because I've also seen many installations just running fine with defaults) and instead, create a PR for the chart to set a higher default there and also adjust any other tunable.

In the end it won't help much if the process waits but Kubernetes kills it anyway. In fact, as it is with this PR, the PostgreSQL **will** be killed after the 10 second timeout. This, of course, might have an impact on a subsequent start-up (recovery), but for that we already have the `POSTGRESQL_INIT_MAX_TIMEOUT`, defaulting to 60 seconds.

2020-10-13 09:53 UTC, rafariossaa commented
Hi,
  Thanks for you PR.
  We currently have in our CI/CD a related change, instead of using `stop_service_using_pid` to stop postgres it will use `pg_ctl stop`.
  Do you think this would solve the timing issue ?

2020-10-13 10:01 UTC, enote-kane commented
@rafariossaa Maybe. Still, we need to have a configurable timeout (e.g. just using the official `PGCTLTIMEOUT`?), so that it can be tweaked for individual needs and higher-level concerns (as for the graceful shutdown in a Kubernetes env).

How exactly is that invocation supposed to be integrated and which customization options are provided? There will be a huge difference especially in the mode of operation for `stop` (`smart` vs. `fast` vs. `immediate`).

2020-10-14 12:54 UTC, rafariossaa commented
Hi,
  We have just released a new version that uses the `pg_ctl stop`.
  Could you check if this work better in you scenario ?
  If you need to indicate a timeout, maybe you can change your PR to include it.

2020-10-14 13:38 UTC, enote-kane commented
OK, I'll have a look at it...

2020-10-14 21:02 UTC, enote-kane commented
Tested the postgresql-ha helm chart with an image containing my revised changes and some tweaks:
```yaml
postgresql:
  extraEnvVars: |
    - name: PGCTLTIMEOUT
      value: "120"
    - name: POSTGRESQL_SHUTDOWN_MODE
      value: "smart"
```
At least that configuration worked for me now in all cases. While mode "fast" is OK and expected for PostgreSQL default behaviour, when used in the context of replication and/or Pgpool-II it can lead to a lot of unwanted log noise. The "smart" mode is better here and actually the only for minimizing the client-side downtime (running queries can finish).

2020-10-15 07:58 UTC, rafariossaa reviewed
I have added some comments. Take into account that I only commented in one of the postgresql version but the same changes should be done in the other versions too.

2020-10-15 07:58 UTC, rafariossaa commented on 10/debian-10/prebuildfs/opt/bitnami/scripts/libservice.sh
>  stop_service_using_pid() {
I guess changes in this file are not needed. Can you remove them ?

2020-10-15 07:58 UTC, rafariossaa commented on 10/debian-10/rootfs/opt/bitnami/scripts/postgresql-env.sh
> +export PGCTLTIMEOUT="${PGCTLTIMEOUT:-60}"
Instead of setting this environment variable here, as it is used by `pg_ctl`, I think it would be better to set it in the `pg_ctl` line the same way `PGDATA` is set

2020-10-15 07:58 UTC, rafariossaa commented on 11/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh
> +        PGDATA="$POSTGRESQL_DATA_DIR" pg_ctl stop -m $POSTGRESQL_SHUTDOWN_MODE -w
Take a look to my comment in `postgresql-env`

2020-10-15 08:35 UTC, enote-kane commented on 10/debian-10/prebuildfs/opt/bitnami/scripts/libservice.sh
>  stop_service_using_pid() {
Well, I thought the might be very useful for any service. But I don't really care in this case. Will drop these changes.

2020-10-15 08:42 UTC, enote-kane commented on 10/debian-10/rootfs/opt/bitnami/scripts/postgresql-env.sh
> +export PGCTLTIMEOUT="${PGCTLTIMEOUT:-60}"
Hm, in that case I'd rather go for using the explicit invocation parameter (`--timeout=<seconds>`) instead of relying on an environment variable. Same actually applies to `PGDATA` (parameter would be `--pgdata=<datadir>`). As long as there is an explicit parameter available, that should be preferred over relying on environment variables, which are picked up or not picked up by a command (in contrast to a parameter, which is either supported or not and would throw an error at you, not silently ignore it).

2020-10-15 08:48 UTC, enote-kane commented on 11/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh
> +        PGDATA="$POSTGRESQL_DATA_DIR" pg_ctl stop -m $POSTGRESQL_SHUTDOWN_MODE -w
Hm, in that case I'd rather go for using the explicit invocation parameter (--timeout=<seconds>) instead of relying on an environment variable. Same actually applies to PGDATA (parameter would be --pgdata=<datadir>). As long as there is an explicit parameter available, that should be preferred over relying on environment variables, which are picked up or not picked up by a command (in contrast to a parameter, which is either supported or not and would throw an error at you, not silently ignore it).

2020-10-16 07:28 UTC, enote-kane commented
@rafariossaa Please have a look at the new change set.

2020-10-26 11:49 UTC, enote-kane commented
@rafariossaa Anything missing from my side?

2020-10-26 11:57 UTC, rafariossaa commented
Hi,
  Sorry for the long delay.
  I am reviewing and testing the changes in our CI/CD.

2020-10-26 12:27 UTC, rafariossaa requested changes

2020-10-26 12:27 UTC, rafariossaa commented on 10/debian-10/rootfs/opt/bitnami/scripts/postgresql-env.sh
> +export PGCTLTIMEOUT="${PGCTLTIMEOUT:-60}"
Hi,
 Do you mind renaming this environment variable as `POSTGRESQL_PGCTLTIMEOUT` ?, this way we have a unified interface in the container as all the "parameters" are `POSTGRESQL_xxxx`.

2020-11-02 08:05 UTC, enote-kane commented
@rafariossaa Any chance to look into the latest changes?

2020-11-06 08:22 UTC, rafariossaa commented
Hi,
 Sorry for the long delay. 
  We implemented some changes in postgresql.  Do you mind rebasing your changes ?

2020-11-09 10:40 UTC, enote-kane commented
@rafariossaa Just updated. Please have a look.

2020-11-11 12:11 UTC, rafariossaa approved these changes
LGTM.
Thank you for you patience.

2020-11-11 12:11 UTC, merged