Add support for repmgr's `location` configuration
bitnami/bitnami-docker-postgresql-repmgr pull request #70
Opened 2021-05-10 02:08 UTC by mrchrisb

**Description of the change**

This PR adds a new environment variable, `REPMGR_NODE_LOCATION` which is used to set the `location` configuration parameter in repmgr.conf.

**Benefits**

The `location` setting is a new feature in repmgr 4 which better facilitates geographically dispersed clusters (https://repmgr.org/docs/4.2/repmgrd-network-split.html for additional details)

Setting this via an environment variable means that the user does not have to go to the additional trouble of using a fully custom configuration file just to be able to set this parameter,

**Possible drawbacks**

None identified

**Applicable issues**

None

**Additional information**

If unset, we use the string `default` as the value for the `location` parameter. This follows repmgr's documented default at https://repmgr.org/docs/4.2/repmgrd-network-split.html.

2021-05-10 09:02 UTC, miguelaeh requested changes
Thank you very much for the PR!!
Please take a look at my comments

2021-05-10 09:02 UTC, miguelaeh commented on 10/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh
> +    local location="${REPMGR_LOCATION:-default}"
This should be added to the `-env.sh` file with the default value and then you can use here just `local location="${REPMGR_LOCATION}"

2021-05-10 22:52 UTC, mrchrisb commented on 10/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh
> +    local location="${REPMGR_LOCATION:-default}"
Yes, that is a great point! This also makes it possible to load the env var from a file for extra flexibility for users. I have added commit `bc261a2` to this effect.

2021-05-12 08:17 UTC, miguelaeh requested changes
Hi @mrchrisb ,
It seems that the env var should be called `REPMGR_NODE_LOCATION` regarding the `README.md`. I already did the changes to reflect this internally but I need you to change all references from `REPMRG_LOCATION` to `REPMGR_NODE_LOCATION` in order to match what our pipeline will release

2021-05-12 23:13 UTC, mrchrisb commented
Corrected, thanks!

2021-05-13 07:44 UTC, miguelaeh approved these changes
LGTM!

2021-05-13 07:44 UTC, merged